"""add_agent_sessions_and_messages

Revision ID: 5928f2a9cf51
Revises: 25b760fbfd74
Create Date: 2026-04-22 11:48:38.173067

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5928f2a9cf51"
down_revision: str | Sequence[str] | None = "25b760fbfd74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("last_modified_date", sa.DateTime(), nullable=False),
        sa.Column("created_by_user_id", sa.String(), nullable=False),
        sa.Column("last_modified_by_user_id", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="sample_schema",
    )
    op.create_index(
        op.f("ix_sample_schema_agent_session_id"),
        "agent_session",
        ["id"],
        unique=False,
        schema="sample_schema",
    )
    op.create_index(
        op.f("ix_sample_schema_agent_session_owner_user_id"),
        "agent_session",
        ["owner_user_id"],
        unique=False,
        schema="sample_schema",
    )
    op.create_table(
        "agent_message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=True),
        sa.Column("tool_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("last_modified_date", sa.DateTime(), nullable=False),
        sa.Column("created_by_user_id", sa.String(), nullable=False),
        sa.Column("last_modified_by_user_id", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tool_call_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sample_schema.agent_session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_agent_message_session_sequence"),
        schema="sample_schema",
    )
    op.create_index(
        op.f("ix_sample_schema_agent_message_id"),
        "agent_message",
        ["id"],
        unique=False,
        schema="sample_schema",
    )
    op.create_index(
        op.f("ix_sample_schema_agent_message_session_id"),
        "agent_message",
        ["session_id"],
        unique=False,
        schema="sample_schema",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sample_schema_agent_message_session_id"),
        table_name="agent_message",
        schema="sample_schema",
    )
    op.drop_index(
        op.f("ix_sample_schema_agent_message_id"),
        table_name="agent_message",
        schema="sample_schema",
    )
    op.drop_table("agent_message", schema="sample_schema")
    op.drop_index(
        op.f("ix_sample_schema_agent_session_owner_user_id"),
        table_name="agent_session",
        schema="sample_schema",
    )
    op.drop_index(
        op.f("ix_sample_schema_agent_session_id"),
        table_name="agent_session",
        schema="sample_schema",
    )
    op.drop_table("agent_session", schema="sample_schema")
    # ### end Alembic commands ###
